@extends('base')

@section('content')
    <div class='main-content-head'>
            <div class="container">
                <div class="row">
                    
                </div>
            </div>
    </div>
    <div class="container" style ='max-width:1263px'>
        <div class="row">
            <div class="partners-detail">
                <div class="partners-head">
                    <h1>Partnership With Us</h1>
                </div>
                <div class="partners-content-1">
                    <div class="content-1-header">
                        <h2>Introducing Broker</h2>
                    </div>
                    <div class="content-1-body">
                        <h4>Stoxtrades Introducing Broker Program is an opportunity for both individuals 
                            and companies to receive a commission for introducing clients to Stoxtrades.
                        </h4>
                        <p>You can earn up to 2 pips commissions for every traded lot generated by the clients referred by you. 
                            Any individual or organization with contacts in the FX trading community 
                            or that has a vast reach to recruit new traders can become a successful Introducer.
                        </p>
                    </div>
                </div>
                <div class="partners-content-2">
                    <div class="content-2-header">
                        <h2>Affiliation</h2>
                    </div>
                    <div class="content-2-body">
                        <h4>The StoxTrades Affiliate Programs are designed to accommodate different types of affiliates. 
                            Whether you are a Webmaster, Individual Trader, EA Developer, or a Marketing firm, 
                            you will find a formula that suits your business model.
                        </h4>
                        <p>As an affiliate, you receive all support needed in order to grow your business, 
                            benefiting from StoxTrades reputation, products, and generous offers.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection